import solarX1 from '../../assets/images/x1/solar-enetgy.webp';
import solarX2 from '../../assets/images/x2/solar-enetgy@2x.webp';
import windX1 from '../../assets/images/x1/wind-energy.webp';
import windX2 from '../../assets/images/x2/wind-energy@2x.webp';
import hydroX1 from '../../assets/images/x1/hydro-energy.webp';
import hydroX2 from '../../assets/images/x2/hydro-energy@2x.webp';
import thermalX1 from '../../assets/images/x1/thermal-energy.webp';
import thermalX2 from '../../assets/images/x2/thermal-energy@2x.webp';
import nuclearX1 from '../../assets/images/x1/nucelar-energy.webp';
import nuclearX2 from '../../assets/images/x2/nucelar-energy@2x.webp';

export const serviceData = [
  {
    title: 'Solar',
    imgX1: solarX1,
    imgX2: solarX2,
    description:
      'Harnessing the power of the sun, solar energy involves converting\nsunlight into electricity through photovoltaic cells, offering a sustainable and renewable energy source.',
  },
  {
    title: 'Wind',
    imgX1: windX1,
    imgX2: windX2,
    description:
      'Branch of alternative energy that specializes in\nconverting the kinetic energy of the wind into electrical energy',
  },
  {
    title: 'Hydro',
    imgX1: hydroX1,
    imgX2: hydroX2,
    description:
      'Derived from the force of moving water, hydro energy is generated by\nconverting the potential and kinetic energy of flowing water into electrical power, contributing to a reliable renewable energy supply.',
  },
  {
    title: 'Thermal',
    imgX1: thermalX1,
    imgX2: thermalX2,
    description:
      'Utilizing heat as its source, thermal energy involves the conversion of\nthermal power into electricity. This form of energy is often harnessed from geothermal, solar, or other heat-producing processes.',
  },
  {
    title: 'Nuclear',
    imgX1: nuclearX1,
    imgX2: nuclearX2,
    description:
      'Fueled by nuclear reactions, nuclear energy involves the controlled release\nof energy from atomic nuclei. It is a powerful and efficient source of electricity with considerations for safety and environmental impact.',
  },
] as const;

export type TService = (typeof serviceData)[number];
